### ISSUE TITLE
ERROR  : The process cannot access the file 'C:\Users\AZURES~1\AppData\Local\Temp\Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO' because it is being used by another process.

### ISSUE THREAD

**Issue by Laborman** [mattmcspirit/azurestack#55] opened 2018-11-07 08:30 UTC
Hey Matt,

It looks like there is a timing issue with the upload of windows images.

I got the following error:

**ERROR  : The process cannot access the file 'C:\Users\AZURES~1\AppData\Local\Temp\Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO' because it is being used by another process.**

**PS>TerminatingError(Get-ChildItem): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\ClusterStorage\Volume1\Images\ServerCore\ServerCore.vhd' because it does not exist."**

Could it be that there is no dependence check on the script, because other parts of the scrip will fail because the image could not be found.

After a rerun it works correct.

**Comment by mattmcspirit** [comment] 2018-11-07 15:00
There are dependency checks built into the script that fail subsequent steps should the image steps (Ubuntu/Core/Full) fail. That's by design. Regarding Core and Full, they execute in parallel and without issue typically. They don't need to dependency check each other, as they only rely on the Windows Update stage having completed previously.

I've not seen any issues with multiple processes accessing the same ISO, however, where did you store it to begin with? Usually for me, the script mounts both as separate DVD drives and does it's job as expected.

Strange it didn't for you...

**Comment by mattmcspirit** [comment] 2018-11-07 17:32
Could you also let me know what your original launch script was, minus any sensitive info?  I'm particularly interested in the ISOpath.

Thanks!

**Comment by mattmcspirit** [comment] 2018-11-16 14:38
Let me know if this is still an issue, else I’ll close this one out.

**Closed** 2018-11-26 19:49 UTC
