### ISSUE TITLE
MySQLVM Deployment fails

### ISSUE THREAD

**Issue by eszych** [mattmcspirit/azurestack#98] opened 2019-07-28 15:17 UTC
**Describe the issue**
MySQLVM deployment fails at stage customscriptextensions:
Deployment failed.
5:02:42 PM - Resource Microsoft.Compute/virtualMachines/extensions 'mysqlhost/CustomScriptExtension' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "Failed to provision VM extensions for VM 'mysqlhost'"
      }
    ]
  }
}'.Exception.Message

Error might be in the install_MySQL8.sh. 
In line #34 (apt-get upgrade -y) there seems to be the "sudo" is missing.
Even after changing that line to "sudo apt-get upgrade -y" the script throws an error when running it manually. The error is related to the "waagent" - recommended action is to run "dpkg --configure -a" manually. After running that command, the install_MySQL8.sh script runs fine...

**Comment by mattmcspirit** [comment] 2019-07-29 04:09
Thanks - this is fixed in the next version (which is not ready for testing) however i've backported it to master, so you should be good to run it again.  The issue isn't with sudo, as the extension runs elevated anyway - it was with the waagent not supporting being upgraded (apt-get upgrade) by the extension itself.

Thanks!

**Closed by mattmcspirit** 2019-07-29 04:09 UTC

**Comment by eszych** [comment] 2019-07-29 05:44
Hello Matt,

thanks for the quick fix - but I guess that does not make sense:
# Update
echo Running apt-get update -y...
sudo apt-get update -y
sudo apt-mark hold walinuxagent
-->  # apt-get upgrade -y <-- marked as comment, line will not run?
sudo apt-mark unhold walinuxagent

Best Regards
Elmar

**Comment by mattmcspirit** [comment] 2019-07-29 13:50
The master version was commented purely because for the MySQL script to run, there is no actual need for apt-get upgrade. You’ll notice the MSSQL script doesn’t use apt-get upgrade either, hence the comment. I’ve seen random issues with upgrade in the past hence the comment.

Glad it worked for you.

**Comment by mattmcspirit** [comment] 2019-07-29 13:52
For reference, the hold and unhold lines prevent a particular package updating, in this case, the waagent, which as mentioned, can’t be upgraded by the extension running.
